---
name: docker-compose-language-service
description: A language server for Docker Compose.
homepage: https://github.com/microsoft/compose-language-service
licenses:
  - MIT
languages:
  - Docker
categories:
  - LSP

source:
  id: pkg:npm/%40microsoft/compose-language-service@0.4.0

bin:
  docker-compose-langserver: npm:docker-compose-langserver

neovim:
  lspconfig: docker_compose_language_service
